<a href="https://colab.research.google.com/github/StephMcCallum/MSE563-SM/blob/main/Feb3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#lattice-mc
#square-lattice MC
#particles to sit on a grid
#calculate energy of your grid
#trial moves that obey detail balance
#have periodic boundary conditions

In [60]:
import numpy as np
import random
#object-oriented approach
class grid():
  #size and particles
  #helper function for neighbor sites to a particle
  def __init__(self,L,N):
    self.sites = np.zeros((L,L))
    self.N = N
    self.L = L
    self.particles = []
    for i in range(self.N):
      self.particles.append(particle(self))
      self.particles[i].location = [random.randint(0,L-1),random.randint(0,L-1)]
      self.sites[self.particles[i].location[0],self.particles[i].location[1]] = 1

  def neighbors(self):
    neighbors = []
    for i,j in range(self.sites):
      if self.sites[i,j] == 1:
        neighbors.append([i+1,j],[i,j+1],[i-1,j],[i,j-1],[i-1,j+1],[i+1,j+1],[i+1,j-1],[i-1,j-1])
    return neighbors

  def microstates(self):
    count = 0
    for i in range(self.L):
        if -1 < (i+1) < self.L:
          if self.sites[i,j] == 1 and self.sites[i+1,j] == 1:
            count += -1
        if -1 < (j+1) < self.L:
          if self.sites[i,j] == 1 and self.sites[i,j+1] == 1:
            count += -1
        if -1 < (i-1) < self.L:
          if self.sites[i,j] == 1 and self.sites[i-1,j] == 1:
            count += -1
        if -1 < (j-1) < self.L:
          if self.sites[i,j] == 1 and self.sites[i,j-1] == 1:
            count += -1
        if 0 > (i+1) >= self.L:
          #update coordinates with pbc
          coor = self.pbc(i+1)
          if self.sites[i,j] == 1 and self.sites[coor,j] == 1:
            count += -1
        if 0 < (j+1) >= self.L:
          coor = self.pbc(j+1)
          if self.sites[i,j] == 1 and self.sites[i,coor] == 1:
            count += -1
        if 0 < (i-1) >= self.L:
          coor = self.pbc(i-1)
          if self.sites[i,j] == 1 and self.sites[coor,j] == 1:
            count += -1
        if 0 < (j-1) >= self.L:
          coor = self.pbc(j-1)
          if self.sites[i,j] == 1 and self.sites[i,coor] == 1:
            count += -1
    E = count//2 #double counts pairs
    return E

    def pbc(self,s):
      if s>=self.L:
        s = s-self.L
      elif s < 0:
        s = s+self.L
      return s

In [54]:
class particle():
  def __init__(self,system):
    self.system = system
    self.location = [0,0]
    system.sites[self.location] == 1

  def available_neighbors(self,system):
    neighbors = []
    for i,j in range(system.L):
      if self.sites[i,j] == 1:
        neighbors.append([i+1,j],[i,j+1],[i-1,j],[i,j-1])
    for ind in neighbors:
      if system.sites[ind] = 1
        neighbors.remove(ind)
      if system.L <= ind[1] < 0:
        ind[0] = system.pbc(ind[0])
      if system.L <= ind[0] < 0:
        ind[1] = system.pbc(ind[1])
    return neighbors

In [63]:
sample_system = grid(4,10)
print(sample_system.sites)
print(sample_system.microstates())

[[0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 1.]
 [0. 0. 0. 1.]]
4 0 0
4 0 1
4 0 2
4 0 3
4 1 0
4 1 1
4 1 2
4 1 3
4 2 0
4 2 1
4 2 2
4 2 3
4 3 0
4 3 1
4 3 2
4 3 3
-5


In [ ]:
import random
import scipy
import math
def sim(N,L,T,trials):
  system = grid(L,N)

  #trial move
  for i in trials:
    random_particle = random.choice(system.N)
    random_location = random.choice(system.neighbors(system.particles[random_particle]))
    copy_system = system
    copy_system.sites[random_location] = 1
    copy_system.sites[system.particles[random_particle].location] = 0
    #calculate energy
    delta_energy = copy_system.microstates() - system.microstates()
    boltzman_weight = - delta_energy / (scipy.constants.k * T)
    if np.random < math.exp(boltzman_weight):
      #accept move
      system = copy_system
    else:
      continue