<a href="https://colab.research.google.com/github/StephMcCallum/MSE563-SM/blob/main/Week_2_Equilibrium_SM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def microstates(system):
  count = 0
  for i in range(grid):
    for j in range(grid):
      if -1 < (i+1) < grid:
        if system[i,j] == 1 and system[i+1,j] == 1:
          count += -1
      if -1 < (j+1) < grid:
        if system[i,j] == 1 and system[i,j+1] == 1:
          count += -1
      if -1 < (i-1) < grid:
        if system[i,j] == 1 and system[i-1,j] == 1:
          count += -1
      if -1 < (j-1) < grid:
        if system[i,j] == 1 and system[i,j-1] == 1:
          count += -1
  E = count//2 #double counts pairs
  print("E =",E)

In [3]:
# Test Code for Figure 2.1
# molecules = 1 in array and empty spaces = 0
E=0
grid = 4
elements = 4
system = np.zeros((grid,grid),dtype=int)
system[0,1] = 1
system[1,2] = 1
print(system)
microstates(system)

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 0]]
E = 0


In [4]:
# Test Code for Figure 2.1
E = 0
grid = 4
elements = 4
system = np.zeros((grid,grid),dtype=int)
system[1,0] = 1
system[1,1] = 1
print(system)
microstates(system)

[[0 0 0 0]
 [1 1 0 0]
 [0 0 0 0]
 [0 0 0 0]]
E = -1


In [5]:
# Test Code for Figure 2.1
E = 0
grid = 4
elements = 4
system = np.zeros((grid,grid),dtype=int)
system[0,0] = 1
system[2,2] = 1
print(system)
microstates(system)

[[1 0 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]]
E = 0


In [6]:
# Test Code for Figure 2.1
# note that function written was for indistguishable molecules
E = 0
grid = 4
elements = 4
system = np.zeros((grid,grid),dtype=int)
system[1,3] = 1
system[2,3] = 1
print(system)
microstates(system)

[[0 0 0 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 0]]
E = -1


In [7]:
#2.8
#combination formula and stirling's approximation
#stirling's approximation = ln(n!) ~ nln(n) - n
#combination formula C = n!/k!(n-k)!
#ln(C) = ln(n!/k!(n-k)!)
#ln(C) = ln(n!) - ln(k!(n-k)!) = ln(n!) - ln(k!) - ln((n-k)!) --> stirling's approximation
#ln(C) = nln(n) - n - kln(k) + k - (n-k)ln(n-k) + n - k --> factor out -n and replace k/n = x
#ln(C) = -n[-ln(n) + xln(k) + (1-x)ln(n-k)]
#ln(C) = -n[(x+1)ln(x) + (1-x)ln(1-x)] #close but I found (x+1) instead of x


In [8]:
#How good is Stirling's approximation?
import math
n = 20
print(math.log(math.factorial(n)))
print("approximation:",(n*math.log(n)-n))

42.335616460753485
approximation: 39.914645471079815


In [9]:
n = 200
print(math.log(math.factorial(n)))
print("approximation:",(n*math.log(n)-n))

863.2319871924054
approximation: 859.6634733096073


In [10]:
n = 2000
print(math.log(math.factorial(n)))
print("approximation:",(n*math.log(n)-n))

13206.524350513806
approximation: 13201.804919084165


In [11]:
##pretty good